package org.vishia.xmlReader.test.genChgSrc;

import java.util.LinkedList;
import java.util.List;

import org.vishia.xmlReader.test.genChgSrc.ClassForBom.BillOfMaterial;
import org.vishia.xmlReader.test.genChgSrc.ClassForBom.Bom_entry;

/**This file is generated by genJavaOut.jzTc script. 
 * It is the derived class to write Zbnf result. */
public class ClassForBom_Zbnf extends ClassForBom{

    /**Creates an instance for the result Zbnf . &lt;BillOfMaterial?BillOfMaterial&gt; for ZBNF data store*/
    public BillOfMaterial_Zbnf new_BillOfMaterial() { 
      BillOfMaterial_Zbnf val = new BillOfMaterial_Zbnf();
      super.billOfMaterial = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;BillOfMaterial?BillOfMaterial&gt;*/
    public void set_BillOfMaterial(BillOfMaterial_Zbnf val) { /*already done: super.billOfMaterial = val; */ }
    
    



  /**Class for Component BillOfMaterial.*/
  public static class BillOfMaterial_Zbnf extends ClassForBom.BillOfMaterial {
  
    /**create and add routine for the list component <Bom_entry?bom_entry>. */
    public Bom_entry_Zbnf new_bom_entry() { 
      Bom_entry_Zbnf val = new Bom_entry_Zbnf(); 
      if(super.bom_entry==null) { super.bom_entry = new LinkedList<Bom_entry>(); }
      super.bom_entry.add(val); 
      return val; 
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Bom_entry?bom_entry&gt;  */
    public Bom_entry_Zbnf new_bom_entry(String bom_count, String bom_footprint, String bom_ordernumber, String bom_part, String bom_value ) { 
      Bom_entry_Zbnf val = new Bom_entry_Zbnf();
      val.bom_count = bom_count;
      val.bom_footprint = bom_footprint;
      val.bom_ordernumber = bom_ordernumber;
      val.bom_part = bom_part;
      val.bom_value = bom_value;
      //
      if(super.bom_entry==null) { super.bom_entry = new LinkedList<Bom_entry>(); }
      super.bom_entry.add(val);
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Add the result to the list. &lt;Bom_entry?bom_entry&gt;*/
    public void add_bom_entry(Bom_entry_Zbnf val) {
      //already done: 
      //if(super.bom_entry==null) { super.bom_entry = new LinkedList<Bom_entry>(); }
      //super.bom_entry.add(val); 
    }
    
    
  
  }




  /**Class for Component Bom_entry.*/
  public static class Bom_entry_Zbnf extends ClassForBom.Bom_entry {
  
    /**Set routine for the singular component &lt;String?bom_count>. */
    public void set_bom_count(String val) { super.bom_count = val; }
    
    
    /**Set routine for the singular component &lt;String?bom_footprint>. */
    public void set_bom_footprint(String val) { super.bom_footprint = val; }
    
    
    /**Set routine for the singular component &lt;String?bom_ordernumber>. */
    public void set_bom_ordernumber(String val) { super.bom_ordernumber = val; }
    
    
    /**Set routine for the singular component &lt;String?bom_part>. */
    public void set_bom_part(String val) { super.bom_part = val; }
    
    
    /**Set routine for the singular component &lt;String?bom_value>. */
    public void set_bom_value(String val) { super.bom_value = val; }
    
    
  
  }


}

