package org.vishia.xmlReader.test.genChgSrc;

import java.util.LinkedList;
import java.util.List;

/**This file is generated by genJavaOut.jzTc script. */
public class ClassForBom {

    
    protected BillOfMaterial billOfMaterial;
    
    
    
    
    /**Access to parse result.*/
    public BillOfMaterial get_BillOfMaterial() { return billOfMaterial; }
    
    



  /**Class for Component BillOfMaterial. */
  public static class BillOfMaterial {
  
    
    protected List<Bom_entry> bom_entry;
    
    
    
    
    /**Access to parse result, get the elements of the container bom_entry*/
    public Iterable<Bom_entry> get_bom_entry() { return bom_entry; }
    
    /**Access to parse result, get the size of the container bom_entry.*/
    public int getSize_bom_entry() { return bom_entry ==null ? 0 : bom_entry.size(); }
    
    
  
  }




  /**Class for Component Bom_entry. */
  public static class Bom_entry {
  
    
    protected String bom_count;
    
    
    
    protected String bom_footprint;
    
    
    
    protected String bom_ordernumber;
    
    
    
    protected String bom_part;
    
    
    
    protected String bom_value;
    
    
    
    
    /**Access to parse result.*/
    public String get_bom_count() { return bom_count; }
    
    
    
    
    /**Access to parse result.*/
    public String get_bom_footprint() { return bom_footprint; }
    
    
    
    
    /**Access to parse result.*/
    public String get_bom_ordernumber() { return bom_ordernumber; }
    
    
    
    
    /**Access to parse result.*/
    public String get_bom_part() { return bom_part; }
    
    
    
    
    /**Access to parse result.*/
    public String get_bom_value() { return bom_value; }
    
    
  
  }


}

