package org.vishia.xmlReader.test;

import java.util.ArrayList;
import java.util.List;

/**This file is generated by genJavaOut.jzTc script. 
 * It is the derived class to write Zbnf result. */
public class Office_odtData_Zbnf extends Office_odtData{

    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Office_document_content?office_document_content&gt; for ZBNF data store*/
    public Office_document_content_Zbnf new_office_document_content() { 
      Office_document_content_Zbnf val = new Office_document_content_Zbnf();
      super.office_document_content = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Office_document_content?office_document_content&gt;  */
    public Office_document_content_Zbnf new_office_document_content(String office_version ) { 
      Office_document_content_Zbnf val = new Office_document_content_Zbnf();
      val.office_version = office_version;
      //
      super.office_document_content = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Office_document_content?office_document_content&gt;*/
    public void set_office_document_content(Office_document_content_Zbnf val) { /*already done: super.office_document_content = val; */ }
    
    



  /**Class for Component Office_document_content.*/
  public static class Office_document_content_Zbnf extends Office_odtData.Office_document_content {
  
    /**Set routine for the singular component &lt;String?office_version>. */
    public void set_office_version(String val) { super.office_version = val; }
    
    
    /**Creates an instance for the result Zbnf . &lt;Office_automatic_styles?office_automatic_styles&gt; for ZBNF data store*/
    public Office_automatic_styles_Zbnf new_office_automatic_styles() { 
      Office_automatic_styles_Zbnf val = new Office_automatic_styles_Zbnf();
      super.office_automatic_styles = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Office_automatic_styles?office_automatic_styles&gt;*/
    public void set_office_automatic_styles(Office_automatic_styles_Zbnf val) { /*already done: super.office_automatic_styles = val; */ }
    
    
    /**Creates an instance for the result Zbnf . &lt;Office_body?office_body&gt; for ZBNF data store*/
    public Office_body_Zbnf new_office_body() { 
      Office_body_Zbnf val = new Office_body_Zbnf();
      super.office_body = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Office_body?office_body&gt;*/
    public void set_office_body(Office_body_Zbnf val) { /*already done: super.office_body = val; */ }
    
    
    /**Creates an instance for the result Zbnf . &lt;Office_font_face_decls?office_font_face_decls&gt; for ZBNF data store*/
    public Office_font_face_decls_Zbnf new_office_font_face_decls() { 
      Office_font_face_decls_Zbnf val = new Office_font_face_decls_Zbnf();
      super.office_font_face_decls = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Office_font_face_decls?office_font_face_decls&gt;*/
    public void set_office_font_face_decls(Office_font_face_decls_Zbnf val) { /*already done: super.office_font_face_decls = val; */ }
    
    
    /**Set routine for the singular component &lt;String?office_scripts>. */
    public void set_office_scripts(String val) { super.office_scripts = val; }
    
    
  
  }




  /**Class for Component Office_automatic_styles.*/
  public static class Office_automatic_styles_Zbnf extends Office_odtData.Office_automatic_styles {
  
    /**create and add routine for the list component <Style_style?style_style>. */
    public Style_style_Zbnf new_style_style() { 
      Style_style_Zbnf val = new Style_style_Zbnf(); 
      if(super.style_style==null) { super.style_style = new ArrayList<Style_style>(); }
      super.style_style.add(val); 
      return val; 
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Style_style?style_style&gt;  */
    public Style_style_Zbnf new_style_style(String style_family, String style_list_style_name, String style_master_page_name, String style_name, String style_parent_style_name ) { 
      Style_style_Zbnf val = new Style_style_Zbnf();
      val.style_family = style_family;
      val.style_list_style_name = style_list_style_name;
      val.style_master_page_name = style_master_page_name;
      val.style_name = style_name;
      val.style_parent_style_name = style_parent_style_name;
      //
      if(super.style_style==null) { super.style_style = new ArrayList<Style_style>(); }
      super.style_style.add(val);
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Add the result to the list. &lt;Style_style?style_style&gt;*/
    public void add_style_style(Style_style_Zbnf val) {
      //already done: 
      //if(super.style_style==null) { super.style_style = new ArrayList<Style_style>(); }
      //super.style_style.add(val); 
    }
    
    
  
  }




  /**Class for Component Office_body.*/
  public static class Office_body_Zbnf extends Office_odtData.Office_body {
  
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Office_text?office_text&gt; for ZBNF data store*/
    public Office_text_Zbnf new_office_text() { 
      Office_text_Zbnf val = new Office_text_Zbnf();
      super.office_text = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Office_text?office_text&gt;  */
    public Office_text_Zbnf new_office_text(String text_use_soft_page_breaks ) { 
      Office_text_Zbnf val = new Office_text_Zbnf();
      val.text_use_soft_page_breaks = text_use_soft_page_breaks;
      //
      super.office_text = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Office_text?office_text&gt;*/
    public void set_office_text(Office_text_Zbnf val) { /*already done: super.office_text = val; */ }
    
    
  
  }




  /**Class for Component Office_font_face_decls.*/
  public static class Office_font_face_decls_Zbnf extends Office_odtData.Office_font_face_decls {
  
    /**create and add routine for the list component <Style_font_face?style_font_face>. */
    public Style_font_face_Zbnf new_style_font_face() { 
      Style_font_face_Zbnf val = new Style_font_face_Zbnf(); 
      if(super.style_font_face==null) { super.style_font_face = new ArrayList<Style_font_face>(); }
      super.style_font_face.add(val); 
      return val; 
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Style_font_face?style_font_face&gt;  */
    public Style_font_face_Zbnf new_style_font_face(String style_font_adornments, String style_font_family_generic, String style_font_pitch, String style_name, String svg_font_family ) { 
      Style_font_face_Zbnf val = new Style_font_face_Zbnf();
      val.style_font_adornments = style_font_adornments;
      val.style_font_family_generic = style_font_family_generic;
      val.style_font_pitch = style_font_pitch;
      val.style_name = style_name;
      val.svg_font_family = svg_font_family;
      //
      if(super.style_font_face==null) { super.style_font_face = new ArrayList<Style_font_face>(); }
      super.style_font_face.add(val);
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Add the result to the list. &lt;Style_font_face?style_font_face&gt;*/
    public void add_style_font_face(Style_font_face_Zbnf val) {
      //already done: 
      //if(super.style_font_face==null) { super.style_font_face = new ArrayList<Style_font_face>(); }
      //super.style_font_face.add(val); 
    }
    
    
  
  }




  /**Class for Component Style_style.*/
  public static class Style_style_Zbnf extends Office_odtData.Style_style {
  
    /**Set routine for the singular component &lt;String?style_family>. */
    public void set_style_family(String val) { super.style_family = val; }
    
    
    /**Set routine for the singular component &lt;String?style_list_style_name>. */
    public void set_style_list_style_name(String val) { super.style_list_style_name = val; }
    
    
    /**Set routine for the singular component &lt;String?style_master_page_name>. */
    public void set_style_master_page_name(String val) { super.style_master_page_name = val; }
    
    
    /**Set routine for the singular component &lt;String?style_name>. */
    public void set_style_name(String val) { super.style_name = val; }
    
    
    /**Set routine for the singular component &lt;String?style_parent_style_name>. */
    public void set_style_parent_style_name(String val) { super.style_parent_style_name = val; }
    
    
    /**Set routine for the singular component &lt;String?loext_graphic_properties>. */
    public void set_loext_graphic_properties(String val) { super.loext_graphic_properties = val; }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Style_paragraph_properties?style_paragraph_properties&gt; for ZBNF data store*/
    public Style_paragraph_properties_Zbnf new_style_paragraph_properties() { 
      Style_paragraph_properties_Zbnf val = new Style_paragraph_properties_Zbnf();
      super.style_paragraph_properties = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Style_paragraph_properties?style_paragraph_properties&gt;  */
    public Style_paragraph_properties_Zbnf new_style_paragraph_properties(String fo_background_color, String fo_break_before, String fo_margin_bottom, String fo_margin_left, String fo_margin_right, String fo_margin_top, String fo_text_align, String fo_text_indent, String loext_contextual_spacing, String style_auto_text_indent, String style_justify_single_word, String style_page_number, String style_writing_mode ) { 
      Style_paragraph_properties_Zbnf val = new Style_paragraph_properties_Zbnf();
      val.fo_background_color = fo_background_color;
      val.fo_break_before = fo_break_before;
      val.fo_margin_bottom = fo_margin_bottom;
      val.fo_margin_left = fo_margin_left;
      val.fo_margin_right = fo_margin_right;
      val.fo_margin_top = fo_margin_top;
      val.fo_text_align = fo_text_align;
      val.fo_text_indent = fo_text_indent;
      val.loext_contextual_spacing = loext_contextual_spacing;
      val.style_auto_text_indent = style_auto_text_indent;
      val.style_justify_single_word = style_justify_single_word;
      val.style_page_number = style_page_number;
      val.style_writing_mode = style_writing_mode;
      //
      super.style_paragraph_properties = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Style_paragraph_properties?style_paragraph_properties&gt;*/
    public void set_style_paragraph_properties(Style_paragraph_properties_Zbnf val) { /*already done: super.style_paragraph_properties = val; */ }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Style_section_properties?style_section_properties&gt; for ZBNF data store*/
    public Style_section_properties_Zbnf new_style_section_properties() { 
      Style_section_properties_Zbnf val = new Style_section_properties_Zbnf();
      super.style_section_properties = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Style_section_properties?style_section_properties&gt;  */
    public Style_section_properties_Zbnf new_style_section_properties(String style_editable ) { 
      Style_section_properties_Zbnf val = new Style_section_properties_Zbnf();
      val.style_editable = style_editable;
      //
      super.style_section_properties = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Style_section_properties?style_section_properties&gt;*/
    public void set_style_section_properties(Style_section_properties_Zbnf val) { /*already done: super.style_section_properties = val; */ }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Style_text_properties?style_text_properties&gt; for ZBNF data store*/
    public Style_text_properties_Zbnf new_style_text_properties() { 
      Style_text_properties_Zbnf val = new Style_text_properties_Zbnf();
      super.style_text_properties = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Style_text_properties?style_text_properties&gt;  */
    public Style_text_properties_Zbnf new_style_text_properties(String fo_country, String fo_font_style, String fo_font_weight, String fo_language, String officeooo_paragraph_rsid, String officeooo_rsid, String style_font_style_asian, String style_font_style_complex, String style_font_weight_asian, String style_font_weight_complex, String style_text_underline_color, String style_text_underline_style, String style_text_underline_width ) { 
      Style_text_properties_Zbnf val = new Style_text_properties_Zbnf();
      val.fo_country = fo_country;
      val.fo_font_style = fo_font_style;
      val.fo_font_weight = fo_font_weight;
      val.fo_language = fo_language;
      val.officeooo_paragraph_rsid = officeooo_paragraph_rsid;
      val.officeooo_rsid = officeooo_rsid;
      val.style_font_style_asian = style_font_style_asian;
      val.style_font_style_complex = style_font_style_complex;
      val.style_font_weight_asian = style_font_weight_asian;
      val.style_font_weight_complex = style_font_weight_complex;
      val.style_text_underline_color = style_text_underline_color;
      val.style_text_underline_style = style_text_underline_style;
      val.style_text_underline_width = style_text_underline_width;
      //
      super.style_text_properties = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Style_text_properties?style_text_properties&gt;*/
    public void set_style_text_properties(Style_text_properties_Zbnf val) { /*already done: super.style_text_properties = val; */ }
    
    
  
  }




  /**Class for Component Office_text.*/
  public static class Office_text_Zbnf extends Office_odtData.Office_text {
  
    /**Set routine for the singular component &lt;String?text_use_soft_page_breaks>. */
    public void set_text_use_soft_page_breaks(String val) { super.text_use_soft_page_breaks = val; }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Office_forms?office_forms&gt; for ZBNF data store*/
    public Office_forms_Zbnf new_office_forms() { 
      Office_forms_Zbnf val = new Office_forms_Zbnf();
      super.office_forms = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Office_forms?office_forms&gt;  */
    public Office_forms_Zbnf new_office_forms(String form_apply_design_mode, String form_automatic_focus ) { 
      Office_forms_Zbnf val = new Office_forms_Zbnf();
      val.form_apply_design_mode = form_apply_design_mode;
      val.form_automatic_focus = form_automatic_focus;
      //
      super.office_forms = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Office_forms?office_forms&gt;*/
    public void set_office_forms(Office_forms_Zbnf val) { /*already done: super.office_forms = val; */ }
    
    
    /**create and add routine for the list component <Text_h?text_h>. */
    public Text_h_Zbnf new_text_h() { 
      Text_h_Zbnf val = new Text_h_Zbnf(); 
      if(super.text_h==null) { super.text_h = new ArrayList<Text_h>(); }
      super.text_h.add(val); 
      return val; 
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_h?text_h&gt;  */
    public Text_h_Zbnf new_text_h(String text_outline_level, String text_style_name ) { 
      Text_h_Zbnf val = new Text_h_Zbnf();
      val.text_outline_level = text_outline_level;
      val.text_style_name = text_style_name;
      //
      if(super.text_h==null) { super.text_h = new ArrayList<Text_h>(); }
      super.text_h.add(val);
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Add the result to the list. &lt;Text_h?text_h&gt;*/
    public void add_text_h(Text_h_Zbnf val) {
      //already done: 
      //if(super.text_h==null) { super.text_h = new ArrayList<Text_h>(); }
      //super.text_h.add(val); 
    }
    
    
    /**create and add routine for the list component <Text_p?text_p>. */
    public Text_p_Zbnf new_text_p() { 
      Text_p_Zbnf val = new Text_p_Zbnf(); 
      if(super.text_p==null) { super.text_p = new ArrayList<Text_p>(); }
      super.text_p.add(val); 
      return val; 
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_p?text_p&gt;  */
    public Text_p_Zbnf new_text_p(String text_style_name ) { 
      Text_p_Zbnf val = new Text_p_Zbnf();
      val.text_style_name = text_style_name;
      //
      if(super.text_p==null) { super.text_p = new ArrayList<Text_p>(); }
      super.text_p.add(val);
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Add the result to the list. &lt;Text_p?text_p&gt;*/
    public void add_text_p(Text_p_Zbnf val) {
      //already done: 
      //if(super.text_p==null) { super.text_p = new ArrayList<Text_p>(); }
      //super.text_p.add(val); 
    }
    
    
    /**Creates an instance for the result Zbnf . &lt;Text_sequence_decls?text_sequence_decls&gt; for ZBNF data store*/
    public Text_sequence_decls_Zbnf new_text_sequence_decls() { 
      Text_sequence_decls_Zbnf val = new Text_sequence_decls_Zbnf();
      super.text_sequence_decls = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_sequence_decls?text_sequence_decls&gt;*/
    public void set_text_sequence_decls(Text_sequence_decls_Zbnf val) { /*already done: super.text_sequence_decls = val; */ }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Text_table_of_content?text_table_of_content&gt; for ZBNF data store*/
    public Text_table_of_content_Zbnf new_text_table_of_content() { 
      Text_table_of_content_Zbnf val = new Text_table_of_content_Zbnf();
      super.text_table_of_content = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_table_of_content?text_table_of_content&gt;  */
    public Text_table_of_content_Zbnf new_text_table_of_content(String text_name, String text_protected, String text_style_name ) { 
      Text_table_of_content_Zbnf val = new Text_table_of_content_Zbnf();
      val.text_name = text_name;
      val.text_protected = text_protected;
      val.text_style_name = text_style_name;
      //
      super.text_table_of_content = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_table_of_content?text_table_of_content&gt;*/
    public void set_text_table_of_content(Text_table_of_content_Zbnf val) { /*already done: super.text_table_of_content = val; */ }
    
    
  
  }




  /**Class for Component Style_font_face.*/
  public static class Style_font_face_Zbnf extends Office_odtData.Style_font_face {
  
    /**Set routine for the singular component &lt;String?style_font_adornments>. */
    public void set_style_font_adornments(String val) { super.style_font_adornments = val; }
    
    
    /**Set routine for the singular component &lt;String?style_font_family_generic>. */
    public void set_style_font_family_generic(String val) { super.style_font_family_generic = val; }
    
    
    /**Set routine for the singular component &lt;String?style_font_pitch>. */
    public void set_style_font_pitch(String val) { super.style_font_pitch = val; }
    
    
    /**Set routine for the singular component &lt;String?style_name>. */
    public void set_style_name(String val) { super.style_name = val; }
    
    
    /**Set routine for the singular component &lt;String?svg_font_family>. */
    public void set_svg_font_family(String val) { super.svg_font_family = val; }
    
    
  
  }




  /**Class for Component Style_paragraph_properties.*/
  public static class Style_paragraph_properties_Zbnf extends Office_odtData.Style_paragraph_properties {
  
    /**Set routine for the singular component &lt;String?fo_background_color>. */
    public void set_fo_background_color(String val) { super.fo_background_color = val; }
    
    
    /**Set routine for the singular component &lt;String?fo_break_before>. */
    public void set_fo_break_before(String val) { super.fo_break_before = val; }
    
    
    /**Set routine for the singular component &lt;String?fo_margin_bottom>. */
    public void set_fo_margin_bottom(String val) { super.fo_margin_bottom = val; }
    
    
    /**Set routine for the singular component &lt;String?fo_margin_left>. */
    public void set_fo_margin_left(String val) { super.fo_margin_left = val; }
    
    
    /**Set routine for the singular component &lt;String?fo_margin_right>. */
    public void set_fo_margin_right(String val) { super.fo_margin_right = val; }
    
    
    /**Set routine for the singular component &lt;String?fo_margin_top>. */
    public void set_fo_margin_top(String val) { super.fo_margin_top = val; }
    
    
    /**Set routine for the singular component &lt;String?fo_text_align>. */
    public void set_fo_text_align(String val) { super.fo_text_align = val; }
    
    
    /**Set routine for the singular component &lt;String?fo_text_indent>. */
    public void set_fo_text_indent(String val) { super.fo_text_indent = val; }
    
    
    /**Set routine for the singular component &lt;String?loext_contextual_spacing>. */
    public void set_loext_contextual_spacing(String val) { super.loext_contextual_spacing = val; }
    
    
    /**Set routine for the singular component &lt;String?style_auto_text_indent>. */
    public void set_style_auto_text_indent(String val) { super.style_auto_text_indent = val; }
    
    
    /**Set routine for the singular component &lt;String?style_justify_single_word>. */
    public void set_style_justify_single_word(String val) { super.style_justify_single_word = val; }
    
    
    /**Set routine for the singular component &lt;String?style_page_number>. */
    public void set_style_page_number(String val) { super.style_page_number = val; }
    
    
    /**Set routine for the singular component &lt;String?style_writing_mode>. */
    public void set_style_writing_mode(String val) { super.style_writing_mode = val; }
    
    
    /**Creates an instance for the result Zbnf . &lt;Style_tab_stops?style_tab_stops&gt; for ZBNF data store*/
    public Style_tab_stops_Zbnf new_style_tab_stops() { 
      Style_tab_stops_Zbnf val = new Style_tab_stops_Zbnf();
      super.style_tab_stops = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Style_tab_stops?style_tab_stops&gt;*/
    public void set_style_tab_stops(Style_tab_stops_Zbnf val) { /*already done: super.style_tab_stops = val; */ }
    
    
  
  }




  /**Class for Component Style_section_properties.*/
  public static class Style_section_properties_Zbnf extends Office_odtData.Style_section_properties {
  
    /**Set routine for the singular component &lt;String?style_editable>. */
    public void set_style_editable(String val) { super.style_editable = val; }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Style_columns?style_columns&gt; for ZBNF data store*/
    public Style_columns_Zbnf new_style_columns() { 
      Style_columns_Zbnf val = new Style_columns_Zbnf();
      super.style_columns = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Style_columns?style_columns&gt;  */
    public Style_columns_Zbnf new_style_columns(String fo_column_count, String fo_column_gap ) { 
      Style_columns_Zbnf val = new Style_columns_Zbnf();
      val.fo_column_count = fo_column_count;
      val.fo_column_gap = fo_column_gap;
      //
      super.style_columns = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Style_columns?style_columns&gt;*/
    public void set_style_columns(Style_columns_Zbnf val) { /*already done: super.style_columns = val; */ }
    
    
  
  }




  /**Class for Component Style_text_properties.*/
  public static class Style_text_properties_Zbnf extends Office_odtData.Style_text_properties {
  
    /**Set routine for the singular component &lt;String?fo_country>. */
    public void set_fo_country(String val) { super.fo_country = val; }
    
    
    /**Set routine for the singular component &lt;String?fo_font_style>. */
    public void set_fo_font_style(String val) { super.fo_font_style = val; }
    
    
    /**Set routine for the singular component &lt;String?fo_font_weight>. */
    public void set_fo_font_weight(String val) { super.fo_font_weight = val; }
    
    
    /**Set routine for the singular component &lt;String?fo_language>. */
    public void set_fo_language(String val) { super.fo_language = val; }
    
    
    /**Set routine for the singular component &lt;String?officeooo_paragraph_rsid>. */
    public void set_officeooo_paragraph_rsid(String val) { super.officeooo_paragraph_rsid = val; }
    
    
    /**Set routine for the singular component &lt;String?officeooo_rsid>. */
    public void set_officeooo_rsid(String val) { super.officeooo_rsid = val; }
    
    
    /**Set routine for the singular component &lt;String?style_font_style_asian>. */
    public void set_style_font_style_asian(String val) { super.style_font_style_asian = val; }
    
    
    /**Set routine for the singular component &lt;String?style_font_style_complex>. */
    public void set_style_font_style_complex(String val) { super.style_font_style_complex = val; }
    
    
    /**Set routine for the singular component &lt;String?style_font_weight_asian>. */
    public void set_style_font_weight_asian(String val) { super.style_font_weight_asian = val; }
    
    
    /**Set routine for the singular component &lt;String?style_font_weight_complex>. */
    public void set_style_font_weight_complex(String val) { super.style_font_weight_complex = val; }
    
    
    /**Set routine for the singular component &lt;String?style_text_underline_color>. */
    public void set_style_text_underline_color(String val) { super.style_text_underline_color = val; }
    
    
    /**Set routine for the singular component &lt;String?style_text_underline_style>. */
    public void set_style_text_underline_style(String val) { super.style_text_underline_style = val; }
    
    
    /**Set routine for the singular component &lt;String?style_text_underline_width>. */
    public void set_style_text_underline_width(String val) { super.style_text_underline_width = val; }
    
    
  
  }




  /**Class for Component Office_forms.*/
  public static class Office_forms_Zbnf extends Office_odtData.Office_forms {
  
    /**Set routine for the singular component &lt;String?form_apply_design_mode>. */
    public void set_form_apply_design_mode(String val) { super.form_apply_design_mode = val; }
    
    
    /**Set routine for the singular component &lt;String?form_automatic_focus>. */
    public void set_form_automatic_focus(String val) { super.form_automatic_focus = val; }
    
    
  
  }




  /**Class for Component Text_h.*/
  public static class Text_h_Zbnf extends Office_odtData.Text_h {
  
    /**Set routine for the singular component &lt;String?text_outline_level>. */
    public void set_text_outline_level(String val) { super.text_outline_level = val; }
    
    
    /**Set routine for the singular component &lt;String?text_style_name>. */
    public void set_text_style_name(String val) { super.text_style_name = val; }
    
    
    /**Set routine for the singular component &lt;String?text_bookmark_end>. */
    public void set_text_bookmark_end(String val) { super.text_bookmark_end = val; }
    
    
    /**Set routine for the singular component &lt;String?text_bookmark_start>. */
    public void set_text_bookmark_start(String val) { super.text_bookmark_start = val; }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Text_span?text_span&gt; for ZBNF data store*/
    public Text_span_Zbnf new_text_span() { 
      Text_span_Zbnf val = new Text_span_Zbnf();
      super.text_span = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_span?text_span&gt;  */
    public Text_span_Zbnf new_text_span(String text_style_name ) { 
      Text_span_Zbnf val = new Text_span_Zbnf();
      val.text_style_name = text_style_name;
      //
      super.text_span = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_span?text_span&gt;*/
    public void set_text_span(Text_span_Zbnf val) { /*already done: super.text_span = val; */ }
    
    
  
  }




  /**Class for Component Text_p.*/
  public static class Text_p_Zbnf extends Office_odtData.Text_p {
  
    /**Set routine for the singular component &lt;String?text_style_name>. */
    public void set_text_style_name(String val) { super.text_style_name = val; }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Text_a?text_a&gt; for ZBNF data store*/
    public Text_a_Zbnf new_text_a() { 
      Text_a_Zbnf val = new Text_a_Zbnf();
      super.text_a = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_a?text_a&gt;  */
    public Text_a_Zbnf new_text_a(String text_style_name, String text_visited_style_name, String xlink_href, String xlink_type ) { 
      Text_a_Zbnf val = new Text_a_Zbnf();
      val.text_style_name = text_style_name;
      val.text_visited_style_name = text_visited_style_name;
      val.xlink_href = xlink_href;
      val.xlink_type = xlink_type;
      //
      super.text_a = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_a?text_a&gt;*/
    public void set_text_a(Text_a_Zbnf val) { /*already done: super.text_a = val; */ }
    
    
    /**create and add routine for the list component <Text_bookmark_ref?text_bookmark_ref>. */
    public Text_bookmark_ref_Zbnf new_text_bookmark_ref() { 
      Text_bookmark_ref_Zbnf val = new Text_bookmark_ref_Zbnf(); 
      if(super.text_bookmark_ref==null) { super.text_bookmark_ref = new ArrayList<Text_bookmark_ref>(); }
      super.text_bookmark_ref.add(val); 
      return val; 
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_bookmark_ref?text_bookmark_ref&gt;  */
    public Text_bookmark_ref_Zbnf new_text_bookmark_ref(String text_ref_name, String text_reference_format ) { 
      Text_bookmark_ref_Zbnf val = new Text_bookmark_ref_Zbnf();
      val.text_ref_name = text_ref_name;
      val.text_reference_format = text_reference_format;
      //
      if(super.text_bookmark_ref==null) { super.text_bookmark_ref = new ArrayList<Text_bookmark_ref>(); }
      super.text_bookmark_ref.add(val);
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Add the result to the list. &lt;Text_bookmark_ref?text_bookmark_ref&gt;*/
    public void add_text_bookmark_ref(Text_bookmark_ref_Zbnf val) {
      //already done: 
      //if(super.text_bookmark_ref==null) { super.text_bookmark_ref = new ArrayList<Text_bookmark_ref>(); }
      //super.text_bookmark_ref.add(val); 
    }
    
    
    /**create and add routine for the list component <Text_s?text_s>. */
    public Text_s_Zbnf new_text_s() { 
      Text_s_Zbnf val = new Text_s_Zbnf(); 
      if(super.text_s==null) { super.text_s = new ArrayList<Text_s>(); }
      super.text_s.add(val); 
      return val; 
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_s?text_s&gt;  */
    public Text_s_Zbnf new_text_s(String text_c ) { 
      Text_s_Zbnf val = new Text_s_Zbnf();
      val.text_c = text_c;
      //
      if(super.text_s==null) { super.text_s = new ArrayList<Text_s>(); }
      super.text_s.add(val);
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Add the result to the list. &lt;Text_s?text_s&gt;*/
    public void add_text_s(Text_s_Zbnf val) {
      //already done: 
      //if(super.text_s==null) { super.text_s = new ArrayList<Text_s>(); }
      //super.text_s.add(val); 
    }
    
    
    /**create and add routine for the list component <Text_span?text_span>. */
    public Text_span_Zbnf new_text_span() { 
      Text_span_Zbnf val = new Text_span_Zbnf(); 
      if(super.text_span==null) { super.text_span = new ArrayList<Text_span>(); }
      super.text_span.add(val); 
      return val; 
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_span?text_span&gt;  */
    public Text_span_Zbnf new_text_span(String text_style_name ) { 
      Text_span_Zbnf val = new Text_span_Zbnf();
      val.text_style_name = text_style_name;
      //
      if(super.text_span==null) { super.text_span = new ArrayList<Text_span>(); }
      super.text_span.add(val);
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Add the result to the list. &lt;Text_span?text_span&gt;*/
    public void add_text_span(Text_span_Zbnf val) {
      //already done: 
      //if(super.text_span==null) { super.text_span = new ArrayList<Text_span>(); }
      //super.text_span.add(val); 
    }
    
    
    /**Set routine for the singular component &lt;String?text_tab>. */
    public void set_text_tab(String val) { super.text_tab = val; }
    
    
  
  }




  /**Class for Component Text_sequence_decls.*/
  public static class Text_sequence_decls_Zbnf extends Office_odtData.Text_sequence_decls {
  
    /**create and add routine for the list component <Text_sequence_decl?text_sequence_decl>. */
    public Text_sequence_decl_Zbnf new_text_sequence_decl() { 
      Text_sequence_decl_Zbnf val = new Text_sequence_decl_Zbnf(); 
      if(super.text_sequence_decl==null) { super.text_sequence_decl = new ArrayList<Text_sequence_decl>(); }
      super.text_sequence_decl.add(val); 
      return val; 
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_sequence_decl?text_sequence_decl&gt;  */
    public Text_sequence_decl_Zbnf new_text_sequence_decl(String text_display_outline_level, String text_name ) { 
      Text_sequence_decl_Zbnf val = new Text_sequence_decl_Zbnf();
      val.text_display_outline_level = text_display_outline_level;
      val.text_name = text_name;
      //
      if(super.text_sequence_decl==null) { super.text_sequence_decl = new ArrayList<Text_sequence_decl>(); }
      super.text_sequence_decl.add(val);
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Add the result to the list. &lt;Text_sequence_decl?text_sequence_decl&gt;*/
    public void add_text_sequence_decl(Text_sequence_decl_Zbnf val) {
      //already done: 
      //if(super.text_sequence_decl==null) { super.text_sequence_decl = new ArrayList<Text_sequence_decl>(); }
      //super.text_sequence_decl.add(val); 
    }
    
    
  
  }




  /**Class for Component Text_table_of_content.*/
  public static class Text_table_of_content_Zbnf extends Office_odtData.Text_table_of_content {
  
    /**Set routine for the singular component &lt;String?text_name>. */
    public void set_text_name(String val) { super.text_name = val; }
    
    
    /**Set routine for the singular component &lt;String?text_protected>. */
    public void set_text_protected(String val) { super.text_protected = val; }
    
    
    /**Set routine for the singular component &lt;String?text_style_name>. */
    public void set_text_style_name(String val) { super.text_style_name = val; }
    
    
    /**Creates an instance for the result Zbnf . &lt;Text_index_body?text_index_body&gt; for ZBNF data store*/
    public Text_index_body_Zbnf new_text_index_body() { 
      Text_index_body_Zbnf val = new Text_index_body_Zbnf();
      super.text_index_body = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_index_body?text_index_body&gt;*/
    public void set_text_index_body(Text_index_body_Zbnf val) { /*already done: super.text_index_body = val; */ }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Text_table_of_content_source?text_table_of_content_source&gt; for ZBNF data store*/
    public Text_table_of_content_source_Zbnf new_text_table_of_content_source() { 
      Text_table_of_content_source_Zbnf val = new Text_table_of_content_source_Zbnf();
      super.text_table_of_content_source = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_table_of_content_source?text_table_of_content_source&gt;  */
    public Text_table_of_content_source_Zbnf new_text_table_of_content_source(String text_outline_level ) { 
      Text_table_of_content_source_Zbnf val = new Text_table_of_content_source_Zbnf();
      val.text_outline_level = text_outline_level;
      //
      super.text_table_of_content_source = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_table_of_content_source?text_table_of_content_source&gt;*/
    public void set_text_table_of_content_source(Text_table_of_content_source_Zbnf val) { /*already done: super.text_table_of_content_source = val; */ }
    
    
  
  }




  /**Class for Component Style_tab_stops.*/
  public static class Style_tab_stops_Zbnf extends Office_odtData.Style_tab_stops {
  
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Style_tab_stop?style_tab_stop&gt; for ZBNF data store*/
    public Style_tab_stop_Zbnf new_style_tab_stop() { 
      Style_tab_stop_Zbnf val = new Style_tab_stop_Zbnf();
      super.style_tab_stop = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Style_tab_stop?style_tab_stop&gt;  */
    public Style_tab_stop_Zbnf new_style_tab_stop(String style_leader_style, String style_leader_text, String style_position, String style_type ) { 
      Style_tab_stop_Zbnf val = new Style_tab_stop_Zbnf();
      val.style_leader_style = style_leader_style;
      val.style_leader_text = style_leader_text;
      val.style_position = style_position;
      val.style_type = style_type;
      //
      super.style_tab_stop = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Style_tab_stop?style_tab_stop&gt;*/
    public void set_style_tab_stop(Style_tab_stop_Zbnf val) { /*already done: super.style_tab_stop = val; */ }
    
    
  
  }




  /**Class for Component Style_columns.*/
  public static class Style_columns_Zbnf extends Office_odtData.Style_columns {
  
    /**Set routine for the singular component &lt;String?fo_column_count>. */
    public void set_fo_column_count(String val) { super.fo_column_count = val; }
    
    
    /**Set routine for the singular component &lt;String?fo_column_gap>. */
    public void set_fo_column_gap(String val) { super.fo_column_gap = val; }
    
    
  
  }




  /**Class for Component Text_span.*/
  public static class Text_span_Zbnf extends Office_odtData.Text_span {
  
    /**Set routine for the singular component &lt;String?text_style_name>. */
    public void set_text_style_name(String val) { super.text_style_name = val; }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Text_bookmark_ref?text_bookmark_ref&gt; for ZBNF data store*/
    public Text_bookmark_ref_Zbnf new_text_bookmark_ref() { 
      Text_bookmark_ref_Zbnf val = new Text_bookmark_ref_Zbnf();
      super.text_bookmark_ref = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_bookmark_ref?text_bookmark_ref&gt;  */
    public Text_bookmark_ref_Zbnf new_text_bookmark_ref(String text_ref_name, String text_reference_format ) { 
      Text_bookmark_ref_Zbnf val = new Text_bookmark_ref_Zbnf();
      val.text_ref_name = text_ref_name;
      val.text_reference_format = text_reference_format;
      //
      super.text_bookmark_ref = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_bookmark_ref?text_bookmark_ref&gt;*/
    public void set_text_bookmark_ref(Text_bookmark_ref_Zbnf val) { /*already done: super.text_bookmark_ref = val; */ }
    
    
    /**Set routine for the singular component &lt;String?text_line_break>. */
    public void set_text_line_break(String val) { super.text_line_break = val; }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Text_s?text_s&gt; for ZBNF data store*/
    public Text_s_Zbnf new_text_s() { 
      Text_s_Zbnf val = new Text_s_Zbnf();
      super.text_s = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_s?text_s&gt;  */
    public Text_s_Zbnf new_text_s(String text_c ) { 
      Text_s_Zbnf val = new Text_s_Zbnf();
      val.text_c = text_c;
      //
      super.text_s = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_s?text_s&gt;*/
    public void set_text_s(Text_s_Zbnf val) { /*already done: super.text_s = val; */ }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Text_span?text_span&gt; for ZBNF data store*/
    public Text_span_Zbnf new_text_span() { 
      Text_span_Zbnf val = new Text_span_Zbnf();
      super.text_span = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_span?text_span&gt;  */
    public Text_span_Zbnf new_text_span(String text_style_name ) { 
      Text_span_Zbnf val = new Text_span_Zbnf();
      val.text_style_name = text_style_name;
      //
      super.text_span = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_span?text_span&gt;*/
    public void set_text_span(Text_span_Zbnf val) { /*already done: super.text_span = val; */ }
    
    
    /**Set routine for the singular component &lt;String?text_tab>. */
    public void set_text_tab(String val) { super.text_tab = val; }
    
    
  
  }




  /**Class for Component Text_a.*/
  public static class Text_a_Zbnf extends Office_odtData.Text_a {
  
    /**Set routine for the singular component &lt;String?text_style_name>. */
    public void set_text_style_name(String val) { super.text_style_name = val; }
    
    
    /**Set routine for the singular component &lt;String?text_visited_style_name>. */
    public void set_text_visited_style_name(String val) { super.text_visited_style_name = val; }
    
    
    /**Set routine for the singular component &lt;String?xlink_href>. */
    public void set_xlink_href(String val) { super.xlink_href = val; }
    
    
    /**Set routine for the singular component &lt;String?xlink_type>. */
    public void set_xlink_type(String val) { super.xlink_type = val; }
    
    
    /**Set routine for the singular component &lt;String?text_s>. */
    public void set_text_s(String val) { super.text_s = val; }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Text_span?text_span&gt; for ZBNF data store*/
    public Text_span_Zbnf new_text_span() { 
      Text_span_Zbnf val = new Text_span_Zbnf();
      super.text_span = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_span?text_span&gt;  */
    public Text_span_Zbnf new_text_span(String text_style_name ) { 
      Text_span_Zbnf val = new Text_span_Zbnf();
      val.text_style_name = text_style_name;
      //
      super.text_span = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_span?text_span&gt;*/
    public void set_text_span(Text_span_Zbnf val) { /*already done: super.text_span = val; */ }
    
    
    /**Set routine for the singular component &lt;String?text_tab>. */
    public void set_text_tab(String val) { super.text_tab = val; }
    
    
  
  }




  /**Class for Component Text_bookmark_ref.*/
  public static class Text_bookmark_ref_Zbnf extends Office_odtData.Text_bookmark_ref {
  
    /**Set routine for the singular component &lt;String?text_ref_name>. */
    public void set_text_ref_name(String val) { super.text_ref_name = val; }
    
    
    /**Set routine for the singular component &lt;String?text_reference_format>. */
    public void set_text_reference_format(String val) { super.text_reference_format = val; }
    
    
  
  }




  /**Class for Component Text_s.*/
  public static class Text_s_Zbnf extends Office_odtData.Text_s {
  
    /**Set routine for the singular component &lt;String?text_c>. */
    public void set_text_c(String val) { super.text_c = val; }
    
    
  
  }




  /**Class for Component Text_sequence_decl.*/
  public static class Text_sequence_decl_Zbnf extends Office_odtData.Text_sequence_decl {
  
    /**Set routine for the singular component &lt;String?text_display_outline_level>. */
    public void set_text_display_outline_level(String val) { super.text_display_outline_level = val; }
    
    
    /**Set routine for the singular component &lt;String?text_name>. */
    public void set_text_name(String val) { super.text_name = val; }
    
    
  
  }




  /**Class for Component Text_index_body.*/
  public static class Text_index_body_Zbnf extends Office_odtData.Text_index_body {
  
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Text_index_title?text_index_title&gt; for ZBNF data store*/
    public Text_index_title_Zbnf new_text_index_title() { 
      Text_index_title_Zbnf val = new Text_index_title_Zbnf();
      super.text_index_title = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_index_title?text_index_title&gt;  */
    public Text_index_title_Zbnf new_text_index_title(String text_name, String text_style_name ) { 
      Text_index_title_Zbnf val = new Text_index_title_Zbnf();
      val.text_name = text_name;
      val.text_style_name = text_style_name;
      //
      super.text_index_title = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_index_title?text_index_title&gt;*/
    public void set_text_index_title(Text_index_title_Zbnf val) { /*already done: super.text_index_title = val; */ }
    
    
    /**create and add routine for the list component <Text_p?text_p>. */
    public Text_p_Zbnf new_text_p() { 
      Text_p_Zbnf val = new Text_p_Zbnf(); 
      if(super.text_p==null) { super.text_p = new ArrayList<Text_p>(); }
      super.text_p.add(val); 
      return val; 
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_p?text_p&gt;  */
    public Text_p_Zbnf new_text_p(String text_style_name ) { 
      Text_p_Zbnf val = new Text_p_Zbnf();
      val.text_style_name = text_style_name;
      //
      if(super.text_p==null) { super.text_p = new ArrayList<Text_p>(); }
      super.text_p.add(val);
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Add the result to the list. &lt;Text_p?text_p&gt;*/
    public void add_text_p(Text_p_Zbnf val) {
      //already done: 
      //if(super.text_p==null) { super.text_p = new ArrayList<Text_p>(); }
      //super.text_p.add(val); 
    }
    
    
  
  }




  /**Class for Component Text_table_of_content_source.*/
  public static class Text_table_of_content_source_Zbnf extends Office_odtData.Text_table_of_content_source {
  
    /**Set routine for the singular component &lt;String?text_outline_level>. */
    public void set_text_outline_level(String val) { super.text_outline_level = val; }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Text_index_title_template?text_index_title_template&gt; for ZBNF data store*/
    public Text_index_title_template_Zbnf new_text_index_title_template() { 
      Text_index_title_template_Zbnf val = new Text_index_title_template_Zbnf();
      super.text_index_title_template = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_index_title_template?text_index_title_template&gt;  */
    public Text_index_title_template_Zbnf new_text_index_title_template(String text_style_name ) { 
      Text_index_title_template_Zbnf val = new Text_index_title_template_Zbnf();
      val.text_style_name = text_style_name;
      //
      super.text_index_title_template = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_index_title_template?text_index_title_template&gt;*/
    public void set_text_index_title_template(Text_index_title_template_Zbnf val) { /*already done: super.text_index_title_template = val; */ }
    
    
    /**create and add routine for the list component <Text_table_of_content_entry_template?text_table_of_content_entry_template>. */
    public Text_table_of_content_entry_template_Zbnf new_text_table_of_content_entry_template() { 
      Text_table_of_content_entry_template_Zbnf val = new Text_table_of_content_entry_template_Zbnf(); 
      if(super.text_table_of_content_entry_template==null) { super.text_table_of_content_entry_template = new ArrayList<Text_table_of_content_entry_template>(); }
      super.text_table_of_content_entry_template.add(val); 
      return val; 
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_table_of_content_entry_template?text_table_of_content_entry_template&gt;  */
    public Text_table_of_content_entry_template_Zbnf new_text_table_of_content_entry_template(String text_outline_level, String text_style_name ) { 
      Text_table_of_content_entry_template_Zbnf val = new Text_table_of_content_entry_template_Zbnf();
      val.text_outline_level = text_outline_level;
      val.text_style_name = text_style_name;
      //
      if(super.text_table_of_content_entry_template==null) { super.text_table_of_content_entry_template = new ArrayList<Text_table_of_content_entry_template>(); }
      super.text_table_of_content_entry_template.add(val);
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Add the result to the list. &lt;Text_table_of_content_entry_template?text_table_of_content_entry_template&gt;*/
    public void add_text_table_of_content_entry_template(Text_table_of_content_entry_template_Zbnf val) {
      //already done: 
      //if(super.text_table_of_content_entry_template==null) { super.text_table_of_content_entry_template = new ArrayList<Text_table_of_content_entry_template>(); }
      //super.text_table_of_content_entry_template.add(val); 
    }
    
    
  
  }




  /**Class for Component Style_tab_stop.*/
  public static class Style_tab_stop_Zbnf extends Office_odtData.Style_tab_stop {
  
    /**Set routine for the singular component &lt;String?style_leader_style>. */
    public void set_style_leader_style(String val) { super.style_leader_style = val; }
    
    
    /**Set routine for the singular component &lt;String?style_leader_text>. */
    public void set_style_leader_text(String val) { super.style_leader_text = val; }
    
    
    /**Set routine for the singular component &lt;String?style_position>. */
    public void set_style_position(String val) { super.style_position = val; }
    
    
    /**Set routine for the singular component &lt;String?style_type>. */
    public void set_style_type(String val) { super.style_type = val; }
    
    
  
  }




  /**Class for Component Text_index_title.*/
  public static class Text_index_title_Zbnf extends Office_odtData.Text_index_title {
  
    /**Set routine for the singular component &lt;String?text_name>. */
    public void set_text_name(String val) { super.text_name = val; }
    
    
    /**Set routine for the singular component &lt;String?text_style_name>. */
    public void set_text_style_name(String val) { super.text_style_name = val; }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Text_p?text_p&gt; for ZBNF data store*/
    public Text_p_Zbnf new_text_p() { 
      Text_p_Zbnf val = new Text_p_Zbnf();
      super.text_p = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_p?text_p&gt;  */
    public Text_p_Zbnf new_text_p(String text_style_name ) { 
      Text_p_Zbnf val = new Text_p_Zbnf();
      val.text_style_name = text_style_name;
      //
      super.text_p = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_p?text_p&gt;*/
    public void set_text_p(Text_p_Zbnf val) { /*already done: super.text_p = val; */ }
    
    
  
  }




  /**Class for Component Text_index_title_template.*/
  public static class Text_index_title_template_Zbnf extends Office_odtData.Text_index_title_template {
  
    /**Set routine for the singular component &lt;String?text_style_name>. */
    public void set_text_style_name(String val) { super.text_style_name = val; }
    
    
  
  }




  /**Class for Component Text_table_of_content_entry_template.*/
  public static class Text_table_of_content_entry_template_Zbnf extends Office_odtData.Text_table_of_content_entry_template {
  
    /**Set routine for the singular component &lt;String?text_outline_level>. */
    public void set_text_outline_level(String val) { super.text_outline_level = val; }
    
    
    /**Set routine for the singular component &lt;String?text_style_name>. */
    public void set_text_style_name(String val) { super.text_style_name = val; }
    
    
    /**Set routine for the singular component &lt;String?text_index_entry_chapter>. */
    public void set_text_index_entry_chapter(String val) { super.text_index_entry_chapter = val; }
    
    
    /**Set routine for the singular component &lt;String?text_index_entry_link_end>. */
    public void set_text_index_entry_link_end(String val) { super.text_index_entry_link_end = val; }
    
    
    /**Set routine for the singular component &lt;String?text_index_entry_link_start>. */
    public void set_text_index_entry_link_start(String val) { super.text_index_entry_link_start = val; }
    
    
    /**Set routine for the singular component &lt;String?text_index_entry_page_number>. */
    public void set_text_index_entry_page_number(String val) { super.text_index_entry_page_number = val; }
    
    
    /**Creates an instance for the result Zbnf  (not Xml) . &lt;Text_index_entry_tab_stop?text_index_entry_tab_stop&gt; for ZBNF data store*/
    public Text_index_entry_tab_stop_Zbnf new_text_index_entry_tab_stop() { 
      Text_index_entry_tab_stop_Zbnf val = new Text_index_entry_tab_stop_Zbnf();
      super.text_index_entry_tab_stop = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Creates an instance for the Xml data storage with default attibutes. &lt;Text_index_entry_tab_stop?text_index_entry_tab_stop&gt;  */
    public Text_index_entry_tab_stop_Zbnf new_text_index_entry_tab_stop(String style_leader_char, String style_type ) { 
      Text_index_entry_tab_stop_Zbnf val = new Text_index_entry_tab_stop_Zbnf();
      val.style_leader_char = style_leader_char;
      val.style_type = style_type;
      //
      super.text_index_entry_tab_stop = val;
      return val; //Note: needs the derived Zbnf-Type.
    }
    
    /**Set the result. &lt;Text_index_entry_tab_stop?text_index_entry_tab_stop&gt;*/
    public void set_text_index_entry_tab_stop(Text_index_entry_tab_stop_Zbnf val) { /*already done: super.text_index_entry_tab_stop = val; */ }
    
    
    /**Set routine for the singular component &lt;String?text_index_entry_text>. */
    public void set_text_index_entry_text(String val) { super.text_index_entry_text = val; }
    
    
  
  }




  /**Class for Component Text_index_entry_tab_stop.*/
  public static class Text_index_entry_tab_stop_Zbnf extends Office_odtData.Text_index_entry_tab_stop {
  
    /**Set routine for the singular component &lt;String?style_leader_char>. */
    public void set_style_leader_char(String val) { super.style_leader_char = val; }
    
    
    /**Set routine for the singular component &lt;String?style_type>. */
    public void set_style_type(String val) { super.style_type = val; }
    
    
  
  }


}

